spring:
  application:
    name: todo

  data:
    mongodb:
      host: localhost
      port: 27017
      database: todo
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /
